begin
  require 'rspec/core/rake_task'
  require 'rubocop/rake_task'

  Dir.glob('tasks/*.rake').each { |rake_file| import rake_file }

  task default: :build

  RSpec::Core::RakeTask.new(:spec) do |task|
    task.rspec_opts = '--format documentation'
  end

  RuboCop::RakeTask.new

  desc 'Build the project executing tests and code formatting'
  task build: [:spec, 'rubocop:auto_correct']

  desc 'Runs unit, integration and feature tests'
  task test_all: [:spec, :features]
rescue LoadError
  puts 'rspec is not available'
end
