source 'https://rubygems.org'

gem 'rack', '1.6.4'
gem 'google-translate', '1.1.2'
gem 'nokogiri', '1.6.6.2'
gem 'shotgun', '0.9.1'
gem 'slim', '3.0.6'

group :test do
  gem 'pry', '~>0.10.1'
  gem 'rack-test', '~>0.6.3'
  gem 'rspec', '~>3.3.0'
  gem 'rubocop', '~>0.33.0'
  gem 'simplecov', '~>0.10.0'
  # gem 'webmock', '~>1.21.0'
end
