source 'https://rubygems.org'

gem 'rack', '1.6.4'

group :test do
  gem 'rack-test', '~>0.6.3'
  gem 'rspec', '~>3.3.0'
  gem 'rubocop', '~>0.33.0'
  gem 'simplecov', '~>0.10.0'
  gem 'webmock', '~>1.21.0'
end
